### ISSUE TITLE
Date format in !ow srgraph

### ISSUE THREAD

**Issue by RavingSombra** [brakhane/Orisa#51]
Recently found that the input date might not be parsed in the correct format, even if following the DD.MM.YYYY or YYYY-MM-DD as specified in the help command.
![imagem](https://user-images.githubusercontent.com/61268574/187083696-ce2134fe-dd10-4164-a348-73161da10d76.png)

After investigating, the `dayfirst=True` argument when parsing the input date works for DD.MM.YYYY but screws up for YYYY-MM-DD. When that arg is not specified, the inverse occurs.

How would this be solved?

- I say either add a regex validation to proceed with or without `dayfirst=True`
- Only accept one of the two formats currently valid 
- Change the supported formats to MM.DD.YYYY or YYYY-MM-DD in the help command (I don't like the month first format for breaking the ISO rules)

**Comment by brakhane** [comment]
Thanks for the bugreport. I'll just use isoparse first and then fall back to parse.
